# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['tucajero/main.py'],
    pathex=['.'],
    binaries=[],
    datas=[
        ('tucajero/ui', 'ui'),
        ('tucajero/models', 'models'),
        ('tucajero/repositories', 'repositories'),
        ('tucajero/services', 'services'),
        ('tucajero/utils', 'utils'),
        ('tucajero/config', 'config'),
        ('tucajero/security', 'security'),
        ('tucajero/app', 'app'),
        ('tucajero/database', 'database'),
        ('tucajero/assets', 'assets'),
        ('tucajero/tools', 'tools'),
    ],
    hiddenimports=[
        'sqlalchemy',
        'sqlalchemy.dialects.sqlite',
        'PySide6.QtCore',
        'PySide6.QtGui',
        'PySide6.QtWidgets',
        'pkg_resources',
        'reportlab',
        'reportlab.lib',
        'reportlab.lib.pagesizes',
        'reportlab.lib.units',
        'reportlab.lib.colors',
        'reportlab.platypus',
        'reportlab.lib.styles',
        'reportlab.lib.enums',
        'openpyxl',
        'PIL',
        'PIL.Image',
        'PIL.ImageDraw',
        'PIL.ImageFont',
        'tucajero.config.database',
        'tucajero.services.corte_service',
        'tucajero.ui.main_window',
        'tucajero.ui.ventas_view',
        'tucajero.models.cliente',
        'tucajero.ui.activate_view',
        'tucajero.security.license_manager',
        'tucajero.utils.store_config',
        'tucajero.container',
        'tucajero.constants',
        'tucajero.repositories.producto_repo',
        'tucajero.repositories.venta_repo',
        'tucajero.repositories.cliente_repo',
        'tucajero.repositories.cajero_repo',
        'tucajero.repositories.proveedor_repo',
        'tucajero.repositories.cotizacion_repo',
        'tucajero.repositories.corte_caja_repo',
        'tucajero.repositories.inventario_repo',
        'tucajero.services.venta_service',
        'tucajero.services.producto_service',
        'tucajero.services.cliente_service',
        'tucajero.services.cajero_service',
        'tucajero.services.proveedor_service',
        'tucajero.services.cotizacion_service',
        'tucajero.services.categoria_service',
        'tucajero.services.historial_service',
        'tucajero.services.fraccion_service',
        'tucajero.services.backup_service',
        'tucajero.domain.events',
        'tucajero.domain.event_dispatcher',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='TuCajero',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
