# -*- mode: python ; coding: utf-8 -*-
from PyInstaller.utils.hooks import collect_data_files

a = Analysis(
    ['tucajero\\main.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('tucajero\\assets', 'assets'),
    ] + collect_data_files('matplotlib'),
    hiddenimports=[
        'PySide6',
        'PySide6.QtCore',
        'PySide6.QtGui',
        'PySide6.QtWidgets',
        'PySide6.QtPrintSupport',
        'sqlalchemy.dialects.sqlite',
        'sqlalchemy.orm',
        'sqlalchemy.sql.default_comparator',
        'reportlab.graphics',
        'reportlab.platypus',
        'reportlab.lib.pagesizes',
        'reportlab.lib.units',
        'reportlab.lib.colors',
        'reportlab.lib.styles',
        'reportlab.lib.enums',
        'openpyxl',
        'openpyxl.styles',
        'openpyxl.utils',
        'openpyxl.writer.excel',
        'matplotlib',
        'matplotlib.backends.backend_qt5agg',
        'matplotlib.figure',
        'numpy',
        'services.categoria_service',
        'services.historial_service',
        'services.cotizacion_service',
        'services.proveedor_service',
        'services.cliente_service',
        'services.cajero_service',
        'utils.factura_diaria',
        'utils.excel_exporter',
        'utils.backup',
        'utils.impresora',
        'models.cotizacion',
        'models.proveedor',
        'models.cliente',
        'models.cajero',
        'escpos.printer',
        'escpos.commandset',
        'escpos.commandset.generic',
        'escpos.exceptions',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'tkinter',
        'unittest',
        'pydoc'
    ],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)
exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='TuCajero',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=['tucajero\\assets\\icons\\tucajero.ico'],
)
